spring.application.name=pms
server.port=8080
#spring.datasource.url=jdbc:oracle:thin:@//192.168.0.23:1521/orcl
#spring.datasource.username=EPISVOC
#Spring.datasource.password=EPISVOC
spring.datasource.url=jdbc:oracle:thin:@//10.12.1.245:1521/orclpdb
spring.datasource.username=EPISVOC
spring.datasource.password=EPISVOC
# Razorpay POS Bridge Configuration
razorpay.pos.base-url=https://demo.ezetap.com/api/3.0/p2padapter
razorpay.pos.app-key=3ad9e1e3-0e61-4dcc-a17a-7864c4afe8fe
razorpay.pos.username=3336661795
razorpay.pos.device-id=1491829348|ezetap_android
razorpay.pos.timeout-seconds=10
# Spring Boot settings
#spring.main.allow-bean-definition-overriding=true