apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpe-backend-deploy
  namespace: dpe-ns
  labels:
    app: dpe-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpe-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: dpe-backend 
    spec:
      containers: 
        - name: dpe-backend-container
          image: cloudwithrk/dpe-backend:latest
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

          # livenessProbe:
          #   tcpSocket:
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 10

          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 10

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: dpe-configmap
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dpe-configmap
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dpe-secret
                  key: SPRING_DATASOURCE_PASSWORD

       
        # - name: ssh-tunnel
        #   image: alpine:latest
        #   command:
        #     - sh
        #     - -c
        #     - |
        #       apk add --no-cache openssh-client && \
        #       chmod 600 /root/.ssh/dpe-key.pem && \
        #       ssh -o StrictHostKeyChecking=no \
        #           -i /root/.ssh/dpe-key.pem \
        #           -N -R 1521:10.12.1.245:1521 \
        #           ubuntu@35.86.96.22
        #   resources:
        #     requests:
        #       cpu: 200m
        #       memory: 128Mi
        #     limits:
        #       cpu: 300m
        #       memory: 256Mi
      #     volumeMounts:
      #       - name: ssh-key-volume
      #         mountPath: /root/.ssh

      # volumes:
      #   - name: ssh-key-volume
      #     secret:
      #       secretName: ssh-key-secret

      restartPolicy: Always
