kind: ConfigMap
apiVersion: v1
metadata:
  name: dpe-configmap
  namespace: dpe-ns
data: 
  SPRING_DATASOURCE_URL: jdbc:oracle:thin:@host.docker.internal:1521:orclpdb
  SPRING_DATASOURCE_USERNAME: EPISVOC 